version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - .:/app
    command: ["node", "server.js"]
  encryptor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["node", "encrypt-images.js"]
