version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./img:/app/img
      - .:/app
    command: sh -c "node /app/server.js & node /app/encrypt-images.js"
