version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./encuestadores.csv:/app/encuestadores.csv
      - ./img:/app/img
